### ISSUE TITLE
Make this play nice with counsel-projectile

### ISSUE THREAD

**Issue by anachronic** [Yevgnen/ivy-rich#2]
I love this enhancement!

Do you think you could make this project play nice with [counsel-projectile](https://github.com/ericdanan/counsel-projectile)? Specifically the switch buffer action.

**Comment by Yevgnen** [comment]
Hi,

Currently you can add something like
```
(ivy-set-display-transformer
 'counsel-projectile-switch-to-buffer 'ivy-switch-buffer-rich-transformer)
```
after loading this package to make it work with `counsel-projectile-switch-to-buffer`. But the project column since a bit redundant if switching buffer in current buffer. Maybe other information can be provided in this situation. Also in other command like `counsel-projectile-switch-project` can also provide extra info motion like project name or vc status. Suggestions on these are welcome. Since switching buffer is the most common command for me, so I only deal with it currently.

**Comment by anachronic** [comment]
I'll give it a try, thanks.
