### ISSUE TITLE
Filter by major mode

### ISSUE THREAD

**Issue by shobute** [Yevgnen/ivy-rich#28]
Great package, thank you!

I would like to filter the buffer list by, for example, the major mode. Helm lets you do this trivially by prefixing the pattern with a star (see: https://github.com/emacs-helm/helm/wiki/Buffers#buffers-by-major-mode). Is this possible with ivy-rich?

**Comment by Yevgnen** [comment]
Hi, thanks for the kind words. 

`ivy-rich` just provide a display transform to the origin candidates. In fact, if you input `emacs-lisp-mode` or something like that, you would get nothing since the origin candidates are buffer names. I think it would be a `ivy-switch-buffer` feature to have search by major-mode etc.

I currently don't know if it's possible to do this in a 'display transformer', but I will dig into it once I have time.

**Comment by shobute** [comment]
Thank you! I guess one solution would be to have buffers automatically renamed to include their major mode, and then filter out the major mode part of the buffer name when displaying, but I feel like that could cause other issues and falls outside of the ivy-rich remit, so closing this issue. :)

**Comment by cjauvin** [comment]
I have proposed a simple [modification](https://github.com/abo-abo/swiper/pull/2936) to ivy which allows to filter based on additional columns supplied by ivy-rich (or any user-supplied transformer function), on a per-command basis (i.e. in my personal case I use it only to modify the behavior of `ivy-switch-buffer`, as the extra cost of computing the transformations on the fly is low enough to be acceptable, which might not be the case with other functions).
