### ISSUE TITLE
Thouhts on adding icons to counsel company?

### ISSUE THREAD

**Issue by jjzmajic** [Yevgnen/ivy-rich#86]
The bulk of the work is already [here](https://github.com/sebastiencs/company-box/blob/master/company-box-icons.el). The question is if this would be a useful addition to the project or something best done in my private config?

**Comment by Yevgnen** [comment]
Sorry for being late. It seems most of dependencies/effort comes from getting icons from different backends, e.g. `(company-box-icons--yasnippet company-box-icons--lsp company-box-icons--elisp company-box-icons--acphp)` of `company-box-icons-functions`. That maybe pretty much for `ivy-rich`. Also, since users use different fonts, the icons comes from default may have alignment issue without fine tuning.

I will suggest take a look of [all-the-icon-ivy-rich](https://github.com/seagle0128/all-the-icons-ivy-rich), that might be a better place to hold the related icons things.

**Comment by seagle0128** [comment]
It has been implemented in https://github.com/seagle0128/all-the-icons-ivy-rich/commit/ba5fb3d22673e50c2807e16dda4fe39c8428b33a.

**Comment by jjzmajic** [comment]
Amazing! Thanks!
